name: Build and Deploy Angular App

on:
  push:
    branches:
      - main 
      - Yml-pages

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up Node.js
        uses: actions/setup-node@v2
    
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Install dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./_site"  

